# ArXiv MCP Enhanced Configuration Example
# This file demonstrates all available configuration options

# Core processing limits
max_downloads: 10
max_extractions: 5
max_compilations: 3

# Rate limiting configuration
requests_per_second: 1.5
burst_size: 10

# Timeout settings (in seconds)
download_timeout: 120
extraction_timeout: 60
compilation_timeout: 600

# Caching settings
cache_ttl: 7200  # 2 hours

# Validation and security
enable_http_validation: true
max_file_size: 209715200  # 200MB
max_files_per_archive: 2000
enable_sandboxing: true

# Output configuration
generate_tex_files: true
output_directory: "/tmp/arxiv_output"
preserve_intermediates: true

# Logging configuration
log_level: "DEBUG"
log_format: "json"
log_file: "/var/log/arxiv_mcp.log"

# External service API keys (leave null if not used)
openai_api_key: null
anthropic_api_key: null
firecrawl_api_key: null
